document.writeln("");
document.writeln("<!--左漂浮-->");
document.writeln("<div id=\"leftfu\" name=\"leftfu\" style=\"position:absolute; left:3px; top:80px;\"> ");
document.writeln("<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("  <tr>");
document.writeln("    <td valign=\"top\"><table width=\"10\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"leftmenu\">");
document.writeln("  <tr>");
document.writeln("    <td><a href=\"javascript:\" onmouseover=\"javascript:showleftmenuover(1);\" onmouseout=\"javascript:showleftmenuout(1);\"><img src=\"qq_Asall.jpg\" border=\"0\"></a></td>");
document.writeln("    </tr>");
document.writeln("  <tr>");
document.writeln("    <td><a href=\"javascript:\" onmouseover=\"javascript:showleftmenuover(2);\" onmouseout=\"javascript:showleftmenuout(2);\"><img src=\"qq_vps.jpg\" border=\"0\" ></a></td>");
document.writeln("    </tr>");
document.writeln("  <tr>");
document.writeln("    <td><a href=\"javascript:\" onmouseover=\"javascript:showleftmenuover(3);\" onmouseout=\"javascript:showleftmenuout(3);\"><img src=\"qq_daili.jpg\" border=\"0\"></a></td>");
document.writeln("    </tr>");
document.writeln("   <tr>");
document.writeln("    <td align=\"right\"><a href=\"javascript:\" onclick=\"javascript:divclose(\'leftmenu\');\"><img src=\"close.jpg\" border=\"0\"></a></td>");
document.writeln("    </tr>");
document.writeln("</table></td>");
document.writeln("	<td valign=\"top\">");
document.writeln("	");
document.writeln("	<div class=\"qqwid\" id=\"showleftmenu_1\" style=\"filter:alpha(opacity=80);z-index:1;\"  onmouseover=\"javascript:showleftmenuover(1);\" onmouseout=\"javascript:showleftmenuout(1);\">");
document.writeln("<div><img src=\"qq_top.png\"></div>");
document.writeln("<div class=\"qqnei\">");
document.writeln("  <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"filter:alpha(opacity=85);\">");
document.writeln("	");

document.writeln("    <tr>");
document.writeln("      <td><img src=http://wpa.qq.com/pa?p=1:319107299:17 height=17 border=0 align=middle><a href=\" http://sighttp.qq.com/cgi-bin/check?sigkey=acadeed6b07fb62d3bbdf1a69b8157952bb2d75abd438fdd77cfa86ce63658e7\"; target=_blank; onclick=\"var tempSrc=\' http://sighttp.qq.com/wpa.js?rantime=\'+Math.random()+\'&sigkey=acadeed6b07fb62d3bbdf1a69b8157952bb2d75abd438fdd77cfa86ce63658e7\';var oldscript=document.getElementById(\'testJs\');var newscript=document.createElement(\'script\');newscript.setAttribute(\'type\',\'text/javascript\'); newscript.setAttribute(\'id\', \'testJs\');newscript.setAttribute(\'src\',tempSrc);if(oldscript == null){document.body.appendChild(newscript);}else{oldscript.parentNode.replaceChild(newscript, oldscript);}return false;\" onmouseover=\"showqqdivover(2)\" onmouseout=\"showqqdivout(2)\">咨询-小赵</a><div id=\"showqq2\" style=\"position:absolute;display:none;z-index:2;filter:alpha(opacity=80);\" onmouseover=\"showqqdivover(2)\" onmouseout=\"showqqdivout(2)\"><table width=\"125\" height=\"45\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#CCCCCC\">");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#FFFFCC\"><div align=\"center\">小赵在线为您服务</div></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#F7F7F7\"><div align=\"center\">QQ:319107299</div></td>");
document.writeln("  </tr>");
document.writeln("</table></div></td>");
document.writeln("      </tr>");
document.writeln("  ");

document.writeln("    <tr>");
document.writeln("      <td><img src=http://wpa.qq.com/pa?p=1:319107296:17 height=17 border=0 align=middle><a href=\" http://sighttp.qq.com/cgi-bin/check?sigkey=969bfab2d063477118e86feafed7a47cf7ec2396d2f48c4cd8e36a6c48de52fb\"; target=_blank; onclick=\"var tempSrc=\' http://sighttp.qq.com/wpa.js?rantime=\'+Math.random()+\'&sigkey=969bfab2d063477118e86feafed7a47cf7ec2396d2f48c4cd8e36a6c48de52fb\';var oldscript=document.getElementById(\'testJs\');var newscript=document.createElement(\'script\');newscript.setAttribute(\'type\',\'text/javascript\'); newscript.setAttribute(\'id\', \'testJs\');newscript.setAttribute(\'src\',tempSrc);if(oldscript == null){document.body.appendChild(newscript);}else{oldscript.parentNode.replaceChild(newscript, oldscript);}return false;\" onmouseover=\"showqqdivover(0)\" onmouseout=\"showqqdivout(0)\">咨询-芳菲</a><div id=\"showqq0\" style=\"position:absolute;display:none;z-index:2;filter:alpha(opacity=80);\" onmouseover=\"showqqdivover(0)\" onmouseout=\"showqqdivout(0)\"><table width=\"125\" height=\"45\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#CCCCCC\">");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#FFFFCC\"><div align=\"center\">芳菲为您服务</div></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#F7F7F7\"><div align=\"center\">QQ:319107296</div></td>");
document.writeln("  </tr>");
document.writeln("</table></div></td>");
document.writeln("      </tr>");
document.writeln("	");

document.writeln("    <tr>");
document.writeln("      <td><img src=http://wpa.qq.com/pa?p=1:319107300:17 height=17 border=0 align=middle><a href=\" http://sighttp.qq.com/cgi-bin/check?sigkey=665a66ba90999059dfc4b7344f8a3fb7bd19aa58009a2cb79e07a08bea4f4d73\"; target=_blank; onclick=\"var tempSrc=\' http://sighttp.qq.com/wpa.js?rantime=\'+Math.random()+\'&sigkey=665a66ba90999059dfc4b7344f8a3fb7bd19aa58009a2cb79e07a08bea4f4d73\';var oldscript=document.getElementById(\'testJs\');var newscript=document.createElement(\'script\');newscript.setAttribute(\'type\',\'text/javascript\'); newscript.setAttribute(\'id\', \'testJs\');newscript.setAttribute(\'src\',tempSrc);if(oldscript == null){document.body.appendChild(newscript);}else{oldscript.parentNode.replaceChild(newscript, oldscript);}return false;\" onmouseover=\"showqqdivover(6)\" onmouseout=\"showqqdivout(6)\">咨询-若诗</a><div id=\"showqq6\" style=\"position:absolute;display:none;z-index:2;filter:alpha(opacity=80);\" onmouseover=\"showqqdivover(6)\" onmouseout=\"showqqdivout(6)\"><table width=\"125\" height=\"45\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#CCCCCC\">");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#FFFFCC\"><div align=\"center\">若诗在线为您服务</div></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#F7F7F7\"><div align=\"center\">QQ:319107300</div></td>");
document.writeln("  </tr>");
document.writeln("</table></div></td>");
document.writeln("      </tr>");
document.writeln("	");

document.writeln("    <tr>");
document.writeln("      <td><img src=http://wpa.qq.com/pa?p=1:712341887:17 height=17 border=0 align=middle><a href=\" http://sighttp.qq.com/cgi-bin/check?sigkey=297529d5ddaef826c7b80b9a86979d90aab57d88da1bc3d6dd4fa3d0b74dcc6f\"; target=_blank; onclick=\"var tempSrc=\' http://sighttp.qq.com/wpa.js?rantime=\'+Math.random()+\'&sigkey=297529d5ddaef826c7b80b9a86979d90aab57d88da1bc3d6dd4fa3d0b74dcc6f\';var oldscript=document.getElementById(\'testJs\');var newscript=document.createElement(\'script\');newscript.setAttribute(\'type\',\'text/javascript\'); newscript.setAttribute(\'id\', \'testJs\');newscript.setAttribute(\'src\',tempSrc);if(oldscript == null){document.body.appendChild(newscript);}else{oldscript.parentNode.replaceChild(newscript, oldscript);}return false;\" onmouseover=\"showqqdivover(103)\" onmouseout=\"showqqdivout(103)\">咨询-小李</a><div id=\"showqq103\" style=\"position:absolute;display:none;z-index:2;filter:alpha(opacity=80);\" onmouseover=\"showqqdivover(103)\" onmouseout=\"showqqdivout(103)\"><table width=\"125\" height=\"45\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#CCCCCC\">");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#FFFFCC\"><div align=\"center\">小李在线为您服务</div></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#F7F7F7\"><div align=\"center\">QQ:712341887</div></td>");
document.writeln("  </tr>");
document.writeln("</table></div></td>");
document.writeln("      </tr>");
document.writeln("	");

document.writeln("    <tr>");
document.writeln("      <td><img src=http://wpa.qq.com/pa?p=1:1607366270:17 height=17 border=0 align=middle><a target=\"_blank\" href=\" http://wpa.qq.com/msgrd?v=3&uin=1607366270&site=qq&menu=yes\" onmouseover=\"showqqdivover(9)\" onmouseout=\"showqqdivout(9)\">紫田-志强</a><div id=\"showqq9\" style=\"position:absolute;display:none;z-index:2;filter:alpha(opacity=80);\" onmouseover=\"showqqdivover(9)\" onmouseout=\"showqqdivout(9)\"><table width=\"125\" height=\"45\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#CCCCCC\">");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#FFFFCC\"><div align=\"center\">志强为您服务</div></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#F7F7F7\"><div align=\"center\">QQ:1607366270</div></td>");
document.writeln("  </tr>");
document.writeln("</table></div></td>");
document.writeln("      </tr>");
document.writeln("	");

document.writeln("    <tr>");
document.writeln("      <td><img src=http://wpa.qq.com/pa?p=1:1654123939:17 height=17 border=0 align=middle><a target=\"_blank\" href=\" http://wpa.qq.com/msgrd?v=3&uin=1654123939&site=qq&menu=yes\" onmouseover=\"showqqdivover(11)\" onmouseout=\"showqqdivout(11)\">紫田-小陈</a><div id=\"showqq11\" style=\"position:absolute;display:none;z-index:2;filter:alpha(opacity=80);\" onmouseover=\"showqqdivover(11)\" onmouseout=\"showqqdivout(11)\"><table width=\"125\" height=\"45\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#CCCCCC\">");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#FFFFCC\"><div align=\"center\">小陈为您服务</div></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#F7F7F7\"><div align=\"center\">QQ:1654123939</div></td>");
document.writeln("  </tr>");
document.writeln("</table></div></td>");
document.writeln("      </tr>");
document.writeln("	");

document.writeln("    <tr>");
document.writeln("      <td><img src=http://wpa.qq.com/pa?p=1:7605658:17 height=17 border=0 align=middle><a href=\"http://sighttp.qq.com/cgi-bin/check?sigkey=56729d161159155e85ed9d03f324ac2e7542898261052b3998a03b6e4493982f\"; target=_blank; onclick=\"var tempSrc=\' http://sighttp.qq.com/wpa.js?rantime=\'+Math.random()+\'&sigkey=56729d161159155e85ed9d03f324ac2e7542898261052b3998a03b6e4493982f\';var oldscript=document.getElementById(\'testJs\');var newscript=document.createElement(\'script\');newscript.setAttribute(\'type\',\'text/javascript\'); newscript.setAttribute(\'id\', \'testJs\');newscript.setAttribute(\'src\',tempSrc);if(oldscript == null){document.body.appendChild(newscript);}else{oldscript.parentNode.replaceChild(newscript, oldscript);}return false;\" onmouseover=\"showqqdivover(1)\" onmouseout=\"showqqdivout(1)\">咨询-雪儿</a><div id=\"showqq1\" style=\"position:absolute;display:none;z-index:2;filter:alpha(opacity=80);\" onmouseover=\"showqqdivover(1)\" onmouseout=\"showqqdivout(1)\"><table width=\"125\" height=\"45\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#CCCCCC\">");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#FFFFCC\"><div align=\"center\">雪儿在线为您服务</div></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#F7F7F7\"><div align=\"center\">QQ:7605658</div></td>");
document.writeln("  </tr>");
document.writeln("</table></div></td>");
document.writeln("      </tr>");
document.writeln("	");

document.writeln("    <tr>");
document.writeln("      <td><img src=http://wpa.qq.com/pa?p=1:319107298:17 height=17 border=0 align=middle><a href=\" http://sighttp.qq.com/cgi-bin/check?sigkey=79d11caab4efd696d124a25b68bb954563af075b497ce87b0e2bf0ac7a9ce339\"; target=_blank; onclick=\"var tempSrc=\' http://sighttp.qq.com/wpa.js?rantime=\'+Math.random()+\'&sigkey=79d11caab4efd696d124a25b68bb954563af075b497ce87b0e2bf0ac7a9ce339\';var oldscript=document.getElementById(\'testJs\');var newscript=document.createElement(\'script\');newscript.setAttribute(\'type\',\'text/javascript\'); newscript.setAttribute(\'id\', \'testJs\');newscript.setAttribute(\'src\',tempSrc);if(oldscript == null){document.body.appendChild(newscript);}else{oldscript.parentNode.replaceChild(newscript, oldscript);}return false;\" onmouseover=\"showqqdivover(10)\" onmouseout=\"showqqdivout(10)\">咨询-小北</a><div id=\"showqq10\" style=\"position:absolute;display:none;z-index:2;filter:alpha(opacity=80);\" onmouseover=\"showqqdivover(10)\" onmouseout=\"showqqdivout(10)\"><table width=\"125\" height=\"45\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#CCCCCC\">");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#FFFFCC\"><div align=\"center\">小北线为您服务</div></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#F7F7F7\"><div align=\"center\">QQ:319107298</div></td>");
document.writeln("  </tr>");
document.writeln("</table></div></td>");
document.writeln("      </tr>");
document.writeln("	");


document.writeln("	");
document.writeln("    <tr>");
document.writeln("      <td>咨询：400-672-0672</td>");
document.writeln("      </tr>");
document.writeln("	");
document.writeln("    <tr>");
document.writeln("      <td><img src=http://wpa.qq.com/pa?p=1:4206439:17 height=17 border=0 align=middle><a href=\" http://sighttp.qq.com/cgi-bin/check?sigkey=a671255ccb98412061140dd5e369928f449c0397a1256330501847c700bb3a86\"; target=_blank; onclick=\"var tempSrc=\' http://sighttp.qq.com/wpa.js?rantime=\'+Math.random()+\'&sigkey=a671255ccb98412061140dd5e369928f449c0397a1256330501847c700bb3a86\';var oldscript=document.getElementById(\'testJs\');var newscript=document.createElement(\'script\');newscript.setAttribute(\'type\',\'text/javascript\'); newscript.setAttribute(\'id\', \'testJs\');newscript.setAttribute(\'src\',tempSrc);if(oldscript == null){document.body.appendChild(newscript);}else{oldscript.parentNode.replaceChild(newscript, oldscript);}return false;\" onmouseover=\"showqqdivover(8)\" onmouseout=\"showqqdivout(8)\">紫田-财务</a><div id=\"showqq8\" style=\"position:absolute;display:none;z-index:2;filter:alpha(opacity=80);\" onmouseover=\"showqqdivover(8)\" onmouseout=\"showqqdivout(8)\"><table width=\"125\" height=\"45\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#CCCCCC\">");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#FFFFCC\"><div align=\"center\">财务在线为您服务</div></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#F7F7F7\"><div align=\"center\">QQ:4206439</div></td>");
document.writeln("  </tr>");
document.writeln("</table></div></td>");
document.writeln("      </tr>");
document.writeln("	");
document.writeln("    <tr>");
document.writeln("      <td>4006-515131转803</td>");
document.writeln("      </tr>");
document.writeln("	");
document.writeln("  </table>");
document.writeln("</div>");
document.writeln("<div style=\"width:100%;border-top:#999 solid 1px;\"><ul style=\"pading:0;margin:5px;color:#333\">QQ临时会话可能会导致消息无法正常接收,请尽量添加客服为好友.</ul></div>");
document.writeln("<div><img src=\"qq_bottom.png\" width=\"142\" height=\"6\"></div>");
document.writeln("</div>");
document.writeln(" ");



document.writeln("	");
document.writeln("	<div class=\"qqwid\" id=\"showleftmenu_2\" style=\"filter:alpha(opacity=80);z-index:1; margin-top:87px; display:none;\"  onmouseover=\"javascript:showleftmenuover(2);\" onmouseout=\"javascript:showleftmenuout(2);\">");
document.writeln("<div><img src=\"qq_top.png\"></div>");
document.writeln("<div class=\"qqnei\">");
document.writeln("  <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"filter:alpha(opacity=85);\">");
document.writeln("  ");
document.writeln("");
document.writeln("	");
document.writeln("    <tr>");
document.writeln("      <td><img src=http://wpa.qq.com/pa?p=1:186943:17 height=17 border=0 align=middle><a href=\"http://sighttp.qq.com/cgi-bin/check?sigkey=048ba2b24989a5ad0be19aeea20fa7a5082f191b4f0051e131e1768b93a3d952\"; target=_blank; onclick=\"var tempSrc=\'http://sighttp.qq.com/wpa.js?rantime=\'+Math.random()+\'&sigkey=048ba2b24989a5ad0be19aeea20fa7a5082f191b4f0051e131e1768b93a3d952\';var oldscript=document.getElementById(\'testJs\');var newscript=document.createElement(\'script\');newscript.setAttribute(\'type\',\'text/javascript\'); newscript.setAttribute(\'id\', \'testJs\');newscript.setAttribute(\'src\',tempSrc);if(oldscript == null){document.body.appendChild(newscript);}else{oldscript.parentNode.replaceChild(newscript, oldscript);}return false;\" onmouseover=\"showqqdivover(21)\" onmouseout=\"showqqdivout(21)\">紫田-古都</a><div id=\"showqq21\" style=\"position:absolute;display:none;z-index:2;filter:alpha(opacity=80);\" onmouseover=\"showqqdivover(21)\" onmouseout=\"showqqdivout(21)\"><table width=\"125\" height=\"45\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#CCCCCC\">");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#FFFFCC\"><div align=\"center\">古都在线为您服务</div></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#F7F7F7\"><div align=\"center\">QQ:186943</div></td>");
document.writeln("  </tr>");
document.writeln("</table></div></td>");
document.writeln("      </tr>");
document.writeln("	");
document.writeln("    <tr>");
document.writeln("      <td><img src=http://wpa.qq.com/pa?p=1:712341872:17 height=17 border=0 align=middle><a href=\"http://sighttp.qq.com/cgi-bin/check?sigkey=93bad3f5ea47613956657ae2ec993e1c1ebed05431b243d507bd805d74f31618\"; target=_blank; onclick=\"var tempSrc=\'http://sighttp.qq.com/wpa.js?rantime=\'+Math.random()+\'&sigkey=93bad3f5ea47613956657ae2ec993e1c1ebed05431b243d507bd805d74f31618\';var oldscript=document.getElementById(\'testJs\');var newscript=document.createElement(\'script\');newscript.setAttribute(\'type\',\'text/javascript\'); newscript.setAttribute(\'id\', \'testJs\');newscript.setAttribute(\'src\',tempSrc);if(oldscript == null){document.body.appendChild(newscript);}else{oldscript.parentNode.replaceChild(newscript, oldscript);}return false;\" onmouseover=\"showqqdivover(20)\" onmouseout=\"showqqdivout(20)\">紫田-小张</a><div id=\"showqq20\" style=\"position:absolute;display:none;z-index:2;filter:alpha(opacity=80);\" onmouseover=\"showqqdivover(20)\" onmouseout=\"showqqdivout(20)\"><table width=\"125\" height=\"45\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#CCCCCC\">");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#FFFFCC\"><div align=\"center\">小张在线为您服务</div></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#F7F7F7\"><div align=\"center\">QQ:712341872</div></td>");
document.writeln("  </tr>");
document.writeln("</table></div></td>");
document.writeln("      </tr>");
document.writeln("	");
document.writeln("    <tr>");
document.writeln("      <td><img border=\"0\" src=\" http://wpa.qq.com/pa?p=1:712341884:17\" alt=\"点击这里给我发消息\" title=\"点击这里给我发消息\"><a target=\"_blank\" href=\" http://wpa.qq.com/msgrd?v=3&uin=712341884&site=qq&menu=yes\">紫田-阿炎</a><div id=\"showqq20\" style=\"position:absolute;display:none;z-index:2;filter:alpha(opacity=80);\" onmouseover=\"showqqdivover(20)\" onmouseout=\"showqqdivout(20)\"><table width=\"125\" height=\"45\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#CCCCCC\">");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#FFFFCC\"><div align=\"center\">阿炎在线为您服务</div></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#F7F7F7\"><div align=\"center\">QQ:712341884</div></td>");
document.writeln("  </tr>");
document.writeln("</table></div></td>");
document.writeln("      </tr>");
document.writeln("	");
document.writeln("    	");
document.writeln("    <tr>");
document.writeln("      <td><img src=http://wpa.qq.com/pa?p=1:712341873:17 height=17 border=0 align=middle><a href=\" http://sighttp.qq.com/cgi-bin/check?sigkey=6c20549199f23a7c587950e1caf7850e2e422ffa9ed5c6a22800e2d159ea9daa\"; target=_blank; onclick=\"var tempSrc=\' http://sighttp.qq.com/wpa.js?rantime=\'+Math.random()+\'&sigkey=6c20549199f23a7c587950e1caf7850e2e422ffa9ed5c6a22800e2d159ea9daa\';var oldscript=document.getElementById(\'testJs\');var newscript=document.createElement(\'script\');newscript.setAttribute(\'type\',\'text/javascript\'); newscript.setAttribute(\'id\', \'testJs\');newscript.setAttribute(\'src\',tempSrc);if(oldscript == null){document.body.appendChild(newscript);}else{oldscript.parentNode.replaceChild(newscript, oldscript);}return false;\" onmouseover=\"showqqdivover(101)\" onmouseout=\"showqqdivout(101)\">紫田-小李</a><div id=\"showqq101\" style=\"position:absolute;display:none;z-index:2;filter:alpha(opacity=80);\" onmouseover=\"showqqdivover(101)\" onmouseout=\"showqqdivout(101)\"><table width=\"125\" height=\"45\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#CCCCCC\">");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#FFFFCC\"><div align=\"center\">小李在线为您服务</div></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#F7F7F7\"><div align=\"center\">QQ:712341873</div></td>");
document.writeln("  </tr>");
document.writeln("</table></div></td>");
document.writeln("      </tr>");
document.writeln("	");
document.writeln("");
document.writeln("    ");
document.writeln("    ");
document.writeln("    <tr>");
document.writeln("      <td>电话：400-672-0672</td>");
document.writeln("      </tr>");
document.writeln("  </table>");
document.writeln("</div>");
document.writeln("<div style=\"width:100%;border-top:#999 solid 1px;\"><ul style=\"pading:0;margin:5px;color:#333\">QQ临时会话可能会导致消息无法正常接收,请尽量添加客服为好友.</ul></div>");
document.writeln("<div><img src=\"qq_bottom.png\" width=\"142\" height=\"6\"></div>");
document.writeln("</div>");
document.writeln(" ");


document.writeln(" ");
document.writeln("<div class=\"qqwid\" id=\"showleftmenu_3\" style=\"filter:alpha(opacity=80);z-index:1; margin-top:174px; display:none;\" onmouseover=\"javascript:showleftmenuover(3);\" onmouseout=\"javascript:showleftmenuout(3);\">");
document.writeln("<div><img src=\"qq_top.png\"></div>");
document.writeln("<div class=\"qqnei\">");
document.writeln("  <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"filter:alpha(opacity=85);\">");
document.writeln("  ");
document.writeln("   <tr>");
document.writeln("      <td><img src=http://wpa.qq.com/pa?p=1:382658:17 height=17 border=0 align=middle><a href=\"http://sighttp.qq.com/cgi-bin/check?sigkey=8ab74771f64e6c0760d3e11e7b180d0086f7c8460d4636d9ea4017709782cc9b\"; target=_blank; onclick=\"var tempSrc=\'http://sighttp.qq.com/wpa.js?rantime=\'+Math.random()+\'&sigkey=8ab74771f64e6c0760d3e11e7b180d0086f7c8460d4636d9ea4017709782cc9b\';var oldscript=document.getElementById(\'testJs\');var newscript=document.createElement(\'script\');newscript.setAttribute(\'type\',\'text/javascript\'); newscript.setAttribute(\'id\', \'testJs\');newscript.setAttribute(\'src\',tempSrc);if(oldscript == null){document.body.appendChild(newscript);}else{oldscript.parentNode.replaceChild(newscript, oldscript);}return false;\" onmouseover=\"showqqdivover(33)\" onmouseout=\"showqqdivout(33)\">紫田—仙子</a><div id=\"showqq33\" style=\"position:absolute;display:none;z-index:2;filter:alpha(opacity=80);\" onmouseover=\"showqqdivover(33)\" onmouseout=\"showqqdivout(33)\"><table width=\"125\" height=\"45\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#CCCCCC\">");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#FFFFCC\"><div align=\"center\">紫田—仙子</div></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#F7F7F7\"><div align=\"center\">QQ:382658</div></td>");
document.writeln("  </tr>");
document.writeln("</table></div></td>");
document.writeln("      </tr>");
document.writeln("	");
document.writeln("    <tr>");
document.writeln("      <td>电话：13323795151</td>");
document.writeln("      </tr>");
document.writeln("  ");
document.writeln("      <tr>");
document.writeln("      <td><img src=http://wpa.qq.com/pa?p=1:271717:17 height=17 border=0 align=middle><a href=\"http://sighttp.qq.com/cgi-bin/check?sigkey=d73afa2a5db715d75c83df4e2a8e85ac04c1d2ee64aa20537d532df49e26be10\"; target=_blank; onclick=\"var tempSrc=\'http://sighttp.qq.com/wpa.js?rantime=\'+Math.random()+\'&sigkey=d73afa2a5db715d75c83df4e2a8e85ac04c1d2ee64aa20537d532df49e26be10\';var oldscript=document.getElementById(\'testJs\');var newscript=document.createElement(\'script\');newscript.setAttribute(\'type\',\'text/javascript\'); newscript.setAttribute(\'id\', \'testJs\');newscript.setAttribute(\'src\',tempSrc);if(oldscript == null){document.body.appendChild(newscript);}else{oldscript.parentNode.replaceChild(newscript, oldscript);}return false;\" onmouseover=\"showqqdivover(32)\" onmouseout=\"showqqdivout(32)\">紫田—徐浩</a><div id=\"showqq32\" style=\"position:absolute;display:none;z-index:2;filter:alpha(opacity=80);\" onmouseover=\"showqqdivover(32)\" onmouseout=\"showqqdivout(32)\"><table width=\"125\" height=\"45\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#CCCCCC\">");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#FFFFCC\"><div align=\"center\">紫田—徐浩</div></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td bgcolor=\"#F7F7F7\"><div align=\"center\">QQ:271717</div></td>");
document.writeln("  </tr>");
document.writeln("</table></div></td>");
document.writeln("      </tr>");
document.writeln("	");
document.writeln("    <tr>");
document.writeln("      <td>电话：15617523999</td>");
document.writeln("      </tr>");
document.writeln("	");
document.writeln("  </table>");
document.writeln("</div>");
document.writeln("<div style=\"width:100%;border-top:#999 solid 1px;\"><ul style=\"pading:0;margin:5px;color:#333\">处理：代理、合作、大客户、投诉、建议等</ul></div>");
document.writeln("<div><img src=\"qq_bottom.png\" width=\"142\" height=\"6\"></div>");
document.writeln("</div>");
document.writeln(" ");
document.writeln(" ");


document.writeln(" ");
document.writeln("</td>");
document.writeln("  </tr>");
document.writeln("</table>");
document.writeln(" ");
document.writeln(" ");
document.writeln(" ");
document.writeln("</div>");
document.writeln("<!--左漂浮-->");



document.writeln("<SCRIPT event=fscommand() for=EccoolAd type=text/javascript></SCRIPT>");
document.writeln("<SCRIPT> ");
document.writeln("	//leftfu.style.visibility=\'hidden\'; ");
document.writeln("	//sorollDiv1.style.visibility=\'hidden\';");
document.writeln("	var lastScrollY=0;");
document.writeln("	var setup=0.02");
document.writeln("	function heartBeat(){ ");
document.writeln("		diffY=document.documentElement.scrollTop; ");
document.writeln("		percent=setup*(diffY-lastScrollY); ");
document.writeln("		if(percent>0)percent=Math.ceil(percent); ");
document.writeln("		else percent=Math.floor(percent); ");
document.writeln("		document.getElementById(\"leftfu\").style.top=parseInt(document.getElementById(\"leftfu\").style.top)+percent+\"px\";");
document.writeln("		lastScrollY=lastScrollY+percent; ");
document.writeln("	}");
document.writeln("	window.setInterval(\"heartBeat()\",1);");
document.writeln("	function divclose(name){");
document.writeln("		document.getElementById(name).style.visibility=\'hidden\';");
document.writeln("	}	");
document.writeln("	function showqqdivover(i)");
document.writeln("{");
document.writeln("document.getElementById(\"showqq\"+i).style.display=\"block\";");
document.writeln("}");
document.writeln("function showqqdivout(i)");
document.writeln("{");
document.writeln("document.getElementById(\"showqq\"+i).style.display=\"none\";");
document.writeln("}");
document.writeln(" ");
document.writeln("function showleftmenuover(id)");
document.writeln("{");
document.writeln("	document.getElementById(\"showleftmenu_\"+id).style.display=\"block\";");
document.writeln("}");
document.writeln(" ");
document.writeln("function showleftmenuout(id)");
document.writeln("{");
document.writeln("	document.getElementById(\"showleftmenu_\"+id).style.display=\"none\";");
document.writeln("}");
document.writeln(" ");
document.writeln("</SCRIPT>");
document.writeln("");
document.writeln("");